Add SortedMap
Yuri364/golang_course_yuri364 pull request #2
Opened 2021-05-30 22:18 UTC by Yuri364

### SortedMap

Сделать пакет `SortedMap` реализующий структуру данных `map`, но с порядком.

Суть этого класса: `map[string]int`, но с сохраненным порядком ключей.
Т.е. мы можем доставать значения из мапы по порядку как их туда записывали.

Использовать его в такой задаче:

Взять [текст] (txt)

Обработать его и найти слова:
- N наиболее употребимых слов из более чем M букв
- не встречающиеся ни в начале ни в конце предложения.
- Вывести в порядке как они встречались в тексте.
- Пунктуацию всю игнорируем (убираем)
- N=10, M=3 для этого текста

[текст]:https://english-e-reader.net/book/gone-with-the-wind-margaret-mitchell

2021-05-31 05:54 UTC, korjavin approved these changes

2021-05-31 05:54 UTC, korjavin commented on go.mod
> +replace github.com/Yuri364/golang_course_yuri364/sortedmap => ./pkg/sortedmap
Лучше поправить импорты

2021-06-02 09:36 UTC, korjavin commented on main.go
> +    reg := regexp.MustCompile(`[^a-zA-Z0-9\s]+`)
тут нет проблемы с regexp?

2021-06-02 14:59 UTC, korjavin requested changes

2021-06-02 14:59 UTC, korjavin commented on main.go
> +				if utf8.RuneCountInString(word) <= charWordLimit || i == 0 || i == len(words)-1 {
Тут слова пропустятся, но суть в том что они должны в стоп-список попасть

2021-06-02 14:59 UTC, korjavin commented on main.go
> +			fmt.Printf("Word '%s' was repeated %d times \n", v, wordStats[v])
для '%s' можно использовать %q (мнемоника  - q - quotes)

2021-06-02 14:59 UTC, korjavin commented on pkg/sortedmap/sortedmap_test.go
> +       _ = sm.GetWordStats(10)
присваивание

2021-06-04 04:29 UTC, Yuri364 commented on main.go
> +    reg := regexp.MustCompile(`[^a-zA-Z0-9\s]+`)
Есть. Вынес в другое место

2021-06-04 04:30 UTC, Yuri364 commented on main.go
> +				if utf8.RuneCountInString(word) <= charWordLimit || i == 0 || i == len(words)-1 {
Спасибо! Именно в этом и была проблема

2021-06-04 04:30 UTC, Yuri364 commented on main.go
> +			fmt.Printf("Word '%s' was repeated %d times \n", v, wordStats[v])
Использовал `%q`

2021-06-04 04:30 UTC, Yuri364 commented on pkg/sortedmap/sortedmap_test.go
> +       _ = sm.GetWordStats(10)
Сделал

2021-06-04 05:35 UTC, korjavin approved these changes

2021-06-04 05:59 UTC, korjavin approved these changes
Урааа!

2021-06-04 05:59 UTC, korjavin commented on pkg/sortedmap/sortedmap.go
> +func (s *SortedMap) AddToStopLIst(word string) {
тут опечатка с регистром I

2021-06-07 05:45 UTC, korjavin commented
Можно мержить думаю

2021-06-09 05:43 UTC, merged